
extern zend_class_entry *moon_component_http_message_session_storage_handler_abstractsessionhandler_ce;

ZEPHIR_INIT_CLASS(Moon_Component_Http_Message_Session_Storage_Handler_AbstractSessionHandler);

PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Handler_AbstractSessionHandler, open);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Handler_AbstractSessionHandler, doRead);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Handler_AbstractSessionHandler, doWrite);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Handler_AbstractSessionHandler, doDestroy);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Handler_AbstractSessionHandler, validateId);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Handler_AbstractSessionHandler, read);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Handler_AbstractSessionHandler, write);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Handler_AbstractSessionHandler, destroy);

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_open, 0, 2, _IS_BOOL, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_open, 0, 2, _IS_BOOL, NULL, 0)
#endif
	ZEND_ARG_INFO(0, savePath)
	ZEND_ARG_INFO(0, sessionName)
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_doread, 0, 1, IS_STRING, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_doread, 0, 1, IS_STRING, NULL, 0)
#endif
#if PHP_VERSION_ID >= 70200
	ZEND_ARG_TYPE_INFO(0, sessionId, IS_STRING, 0)
#else
	ZEND_ARG_INFO(0, sessionId)
#endif
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_dowrite, 0, 2, _IS_BOOL, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_dowrite, 0, 2, _IS_BOOL, NULL, 0)
#endif
#if PHP_VERSION_ID >= 70200
	ZEND_ARG_TYPE_INFO(0, sessionId, IS_STRING, 0)
#else
	ZEND_ARG_INFO(0, sessionId)
#endif
#if PHP_VERSION_ID >= 70200
	ZEND_ARG_TYPE_INFO(0, data, IS_STRING, 0)
#else
	ZEND_ARG_INFO(0, data)
#endif
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_dodestroy, 0, 1, _IS_BOOL, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_dodestroy, 0, 1, _IS_BOOL, NULL, 0)
#endif
#if PHP_VERSION_ID >= 70200
	ZEND_ARG_TYPE_INFO(0, sessionId, IS_STRING, 0)
#else
	ZEND_ARG_INFO(0, sessionId)
#endif
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_validateid, 0, 1, _IS_BOOL, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_validateid, 0, 1, _IS_BOOL, NULL, 0)
#endif
	ZEND_ARG_INFO(0, sessionId)
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_read, 0, 1, IS_STRING, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_read, 0, 1, IS_STRING, NULL, 0)
#endif
	ZEND_ARG_INFO(0, sessionId)
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_write, 0, 2, _IS_BOOL, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_write, 0, 2, _IS_BOOL, NULL, 0)
#endif
	ZEND_ARG_INFO(0, sessionId)
	ZEND_ARG_INFO(0, data)
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_destroy, 0, 1, _IS_BOOL, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_destroy, 0, 1, _IS_BOOL, NULL, 0)
#endif
	ZEND_ARG_INFO(0, sessionId)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(moon_component_http_message_session_storage_handler_abstractsessionhandler_method_entry) {
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Handler_AbstractSessionHandler, open, arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_open, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Handler_AbstractSessionHandler, doRead, arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_doread, ZEND_ACC_PROTECTED|ZEND_ACC_ABSTRACT)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Handler_AbstractSessionHandler, doWrite, arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_dowrite, ZEND_ACC_PROTECTED|ZEND_ACC_ABSTRACT)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Handler_AbstractSessionHandler, doDestroy, arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_dodestroy, ZEND_ACC_PROTECTED|ZEND_ACC_ABSTRACT)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Handler_AbstractSessionHandler, validateId, arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_validateid, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Handler_AbstractSessionHandler, read, arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_read, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Handler_AbstractSessionHandler, write, arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_write, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Handler_AbstractSessionHandler, destroy, arginfo_moon_component_http_message_session_storage_handler_abstractsessionhandler_destroy, ZEND_ACC_PUBLIC)
	PHP_FE_END
};
