
extern zend_class_entry *moon_component_http_message_session_storage_handler_migratingsessionhandler_ce;

ZEPHIR_INIT_CLASS(Moon_Component_Http_Message_Session_Storage_Handler_MigratingSessionHandler);

PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Handler_MigratingSessionHandler, __construct);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Handler_MigratingSessionHandler, close);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Handler_MigratingSessionHandler, destroy);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Handler_MigratingSessionHandler, gc);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Handler_MigratingSessionHandler, open);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Handler_MigratingSessionHandler, read);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Handler_MigratingSessionHandler, write);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Handler_MigratingSessionHandler, validateId);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Handler_MigratingSessionHandler, updateTimestamp);

ZEND_BEGIN_ARG_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler___construct, 0, 0, 2)
	ZEND_ARG_OBJ_INFO(0, currentHandler, SessionHandlerInterface, 0)
	ZEND_ARG_OBJ_INFO(0, writeOnlyHandler, SessionHandlerInterface, 0)
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_close, 0, 0, _IS_BOOL, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_close, 0, 0, _IS_BOOL, NULL, 0)
#endif
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_destroy, 0, 1, _IS_BOOL, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_destroy, 0, 1, _IS_BOOL, NULL, 0)
#endif
	ZEND_ARG_INFO(0, sessionId)
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_gc, 0, 1, _IS_BOOL, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_gc, 0, 1, _IS_BOOL, NULL, 0)
#endif
	ZEND_ARG_INFO(0, maxlifetime)
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_open, 0, 2, _IS_BOOL, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_open, 0, 2, _IS_BOOL, NULL, 0)
#endif
	ZEND_ARG_INFO(0, savePath)
	ZEND_ARG_INFO(0, sessionName)
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_read, 0, 1, IS_STRING, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_read, 0, 1, IS_STRING, NULL, 0)
#endif
	ZEND_ARG_INFO(0, sessionId)
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_write, 0, 2, _IS_BOOL, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_write, 0, 2, _IS_BOOL, NULL, 0)
#endif
	ZEND_ARG_INFO(0, sessionId)
	ZEND_ARG_INFO(0, sessionData)
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_validateid, 0, 1, _IS_BOOL, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_validateid, 0, 1, _IS_BOOL, NULL, 0)
#endif
	ZEND_ARG_INFO(0, sessionId)
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_updatetimestamp, 0, 2, _IS_BOOL, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_updatetimestamp, 0, 2, _IS_BOOL, NULL, 0)
#endif
	ZEND_ARG_INFO(0, sessionId)
	ZEND_ARG_INFO(0, sessionData)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(moon_component_http_message_session_storage_handler_migratingsessionhandler_method_entry) {
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Handler_MigratingSessionHandler, __construct, arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Handler_MigratingSessionHandler, close, arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_close, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Handler_MigratingSessionHandler, destroy, arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_destroy, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Handler_MigratingSessionHandler, gc, arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_gc, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Handler_MigratingSessionHandler, open, arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_open, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Handler_MigratingSessionHandler, read, arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_read, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Handler_MigratingSessionHandler, write, arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_write, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Handler_MigratingSessionHandler, validateId, arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_validateid, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Handler_MigratingSessionHandler, updateTimestamp, arginfo_moon_component_http_message_session_storage_handler_migratingsessionhandler_updatetimestamp, ZEND_ACC_PUBLIC)
	PHP_FE_END
};
