
extern zend_class_entry *moon_component_http_message_session_storage_handler_nativefilesessionhandler_ce;

ZEPHIR_INIT_CLASS(Moon_Component_Http_Message_Session_Storage_Handler_NativeFileSessionHandler);

PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Handler_NativeFileSessionHandler, __construct);

ZEND_BEGIN_ARG_INFO_EX(arginfo_moon_component_http_message_session_storage_handler_nativefilesessionhandler___construct, 0, 0, 0)
#if PHP_VERSION_ID >= 70200
	ZEND_ARG_TYPE_INFO(0, savePath, IS_STRING, 1)
#else
	ZEND_ARG_INFO(0, savePath)
#endif
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(moon_component_http_message_session_storage_handler_nativefilesessionhandler_method_entry) {
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Handler_NativeFileSessionHandler, __construct, arginfo_moon_component_http_message_session_storage_handler_nativefilesessionhandler___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_FE_END
};
