
extern zend_class_entry *moon_component_http_message_session_storage_proxy_abstractproxy_ce;

ZEPHIR_INIT_CLASS(Moon_Component_Http_Message_Session_Storage_Proxy_AbstractProxy);

PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Proxy_AbstractProxy, getSaveHandlerName);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Proxy_AbstractProxy, isSessionHandlerInterface);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Proxy_AbstractProxy, isWrapper);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Proxy_AbstractProxy, isActive);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Proxy_AbstractProxy, getId);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Proxy_AbstractProxy, setId);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Proxy_AbstractProxy, getName);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_Proxy_AbstractProxy, setName);

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_proxy_abstractproxy_getsavehandlername, 0, 0, IS_STRING, 1)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_proxy_abstractproxy_getsavehandlername, 0, 0, IS_STRING, NULL, 1)
#endif
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_proxy_abstractproxy_issessionhandlerinterface, 0, 0, _IS_BOOL, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_proxy_abstractproxy_issessionhandlerinterface, 0, 0, _IS_BOOL, NULL, 0)
#endif
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_proxy_abstractproxy_iswrapper, 0, 0, _IS_BOOL, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_proxy_abstractproxy_iswrapper, 0, 0, _IS_BOOL, NULL, 0)
#endif
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_proxy_abstractproxy_isactive, 0, 0, _IS_BOOL, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_proxy_abstractproxy_isactive, 0, 0, _IS_BOOL, NULL, 0)
#endif
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_proxy_abstractproxy_getid, 0, 0, IS_STRING, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_proxy_abstractproxy_getid, 0, 0, IS_STRING, NULL, 0)
#endif
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_moon_component_http_message_session_storage_proxy_abstractproxy_setid, 0, 0, 1)
#if PHP_VERSION_ID >= 70200
	ZEND_ARG_TYPE_INFO(0, id, IS_STRING, 0)
#else
	ZEND_ARG_INFO(0, id)
#endif
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_proxy_abstractproxy_getname, 0, 0, IS_STRING, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_proxy_abstractproxy_getname, 0, 0, IS_STRING, NULL, 0)
#endif
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_moon_component_http_message_session_storage_proxy_abstractproxy_setname, 0, 0, 1)
#if PHP_VERSION_ID >= 70200
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
#else
	ZEND_ARG_INFO(0, name)
#endif
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(moon_component_http_message_session_storage_proxy_abstractproxy_method_entry) {
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Proxy_AbstractProxy, getSaveHandlerName, arginfo_moon_component_http_message_session_storage_proxy_abstractproxy_getsavehandlername, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Proxy_AbstractProxy, isSessionHandlerInterface, arginfo_moon_component_http_message_session_storage_proxy_abstractproxy_issessionhandlerinterface, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Proxy_AbstractProxy, isWrapper, arginfo_moon_component_http_message_session_storage_proxy_abstractproxy_iswrapper, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Proxy_AbstractProxy, isActive, arginfo_moon_component_http_message_session_storage_proxy_abstractproxy_isactive, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Proxy_AbstractProxy, getId, arginfo_moon_component_http_message_session_storage_proxy_abstractproxy_getid, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Proxy_AbstractProxy, setId, arginfo_moon_component_http_message_session_storage_proxy_abstractproxy_setid, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Proxy_AbstractProxy, getName, arginfo_moon_component_http_message_session_storage_proxy_abstractproxy_getname, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_Proxy_AbstractProxy, setName, arginfo_moon_component_http_message_session_storage_proxy_abstractproxy_setname, ZEND_ACC_PUBLIC)
	PHP_FE_END
};
