
extern zend_class_entry *moon_component_errorhandler_formatter_callbackformatter_ce;

ZEPHIR_INIT_CLASS(Moon_Component_ErrorHandler_Formatter_CallbackFormatter);

PHP_METHOD(Moon_Component_ErrorHandler_Formatter_CallbackFormatter, __construct);
PHP_METHOD(Moon_Component_ErrorHandler_Formatter_CallbackFormatter, format);

ZEND_BEGIN_ARG_INFO_EX(arginfo_moon_component_errorhandler_formatter_callbackformatter___construct, 0, 0, 1)
	ZEND_ARG_INFO(0, _callable)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_moon_component_errorhandler_formatter_callbackformatter_format, 0, 0, 3)
	ZEND_ARG_OBJ_INFO(0, exception, Throwable, 0)
	ZEND_ARG_INFO(0, debug)
	ZEND_ARG_INFO(0, charset)
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(moon_component_errorhandler_formatter_callbackformatter_method_entry) {
	PHP_ME(Moon_Component_ErrorHandler_Formatter_CallbackFormatter, __construct, arginfo_moon_component_errorhandler_formatter_callbackformatter___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_ME(Moon_Component_ErrorHandler_Formatter_CallbackFormatter, format, arginfo_moon_component_errorhandler_formatter_callbackformatter_format, ZEND_ACC_PUBLIC)
	PHP_FE_END
};
