
extern zend_class_entry *moon_component_http_message_session_storage_mockarraysessionstorage_ce;

ZEPHIR_INIT_CLASS(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage);

PHP_METHOD(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, __construct);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, setSessionData);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, start);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, regenerate);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, getId);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, setId);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, getName);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, setName);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, save);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, clear);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, registerBag);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, getBag);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, isStarted);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, setMetadataBag);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, getMetadataBag);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, generateId);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, loadSession);
zend_object *zephir_init_properties_Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage(zend_class_entry *class_type TSRMLS_DC);

ZEND_BEGIN_ARG_INFO_EX(arginfo_moon_component_http_message_session_storage_mockarraysessionstorage___construct, 0, 0, 1)
#if PHP_VERSION_ID >= 70200
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
#else
	ZEND_ARG_INFO(0, name)
#endif
	ZEND_ARG_OBJ_INFO(0, metaBag, Moon\\Component\\Http\\Message\\Session\\Storage\\MetadataBag, 0)
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_setsessiondata, 0, 0, 1)
	ZEND_ARG_ARRAY_INFO(0, _array, 0)
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_start, 0, 0, _IS_BOOL, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_start, 0, 0, _IS_BOOL, NULL, 0)
#endif
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_regenerate, 0, 0, _IS_BOOL, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_regenerate, 0, 0, _IS_BOOL, NULL, 0)
#endif
#if PHP_VERSION_ID >= 70200
	ZEND_ARG_TYPE_INFO(0, destroy, _IS_BOOL, 0)
#else
	ZEND_ARG_INFO(0, destroy)
#endif
#if PHP_VERSION_ID >= 70200
	ZEND_ARG_TYPE_INFO(0, lifetime, IS_LONG, 1)
#else
	ZEND_ARG_INFO(0, lifetime)
#endif
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_getid, 0, 0, IS_STRING, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_getid, 0, 0, IS_STRING, NULL, 0)
#endif
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_setid, 0, 0, 1)
#if PHP_VERSION_ID >= 70200
	ZEND_ARG_TYPE_INFO(0, id, IS_STRING, 0)
#else
	ZEND_ARG_INFO(0, id)
#endif
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_getname, 0, 0, IS_STRING, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_getname, 0, 0, IS_STRING, NULL, 0)
#endif
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_setname, 0, 0, 1)
#if PHP_VERSION_ID >= 70200
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
#else
	ZEND_ARG_INFO(0, name)
#endif
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_registerbag, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, bag, Moon\\Component\\Http\\Message\\Session\\SessionBagInterface, 0)
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_getbag, 0, 1, Moon\\Component\\Http\\Message\\Session\\SessionBagInterface, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_getbag, 0, 1, IS_OBJECT, "Moon\\Component\\Http\\Message\\Session\\SessionBagInterface", 0)
#endif
#if PHP_VERSION_ID >= 70200
	ZEND_ARG_TYPE_INFO(0, name, IS_STRING, 0)
#else
	ZEND_ARG_INFO(0, name)
#endif
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_isstarted, 0, 0, _IS_BOOL, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_isstarted, 0, 0, _IS_BOOL, NULL, 0)
#endif
ZEND_END_ARG_INFO()

ZEND_BEGIN_ARG_INFO_EX(arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_setmetadatabag, 0, 0, 1)
	ZEND_ARG_OBJ_INFO(0, bag, Moon\\Component\\Http\\Message\\Session\\Storage\\MetadataBag, 0)
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_getmetadatabag, 0, 0, Moon\\Component\\Http\\Message\\Session\\Storage\\MetadataBag, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_getmetadatabag, 0, 0, IS_OBJECT, "Moon\\Component\\Http\\Message\\Session\\Storage\\MetadataBag", 0)
#endif
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_generateid, 0, 0, IS_STRING, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_generateid, 0, 0, IS_STRING, NULL, 0)
#endif
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(moon_component_http_message_session_storage_mockarraysessionstorage_method_entry) {
	PHP_ME(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, __construct, arginfo_moon_component_http_message_session_storage_mockarraysessionstorage___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, setSessionData, arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_setsessiondata, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, start, arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_start, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, regenerate, arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_regenerate, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, getId, arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_getid, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, setId, arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_setid, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, getName, arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_getname, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, setName, arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_setname, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, save, NULL, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, clear, NULL, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, registerBag, arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_registerbag, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, getBag, arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_getbag, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, isStarted, arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_isstarted, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, setMetadataBag, arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_setmetadatabag, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, getMetadataBag, arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_getmetadatabag, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, generateId, arginfo_moon_component_http_message_session_storage_mockarraysessionstorage_generateid, ZEND_ACC_PROTECTED)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_MockArraySessionStorage, loadSession, NULL, ZEND_ACC_PROTECTED)
	PHP_FE_END
};
