
extern zend_class_entry *moon_component_http_message_session_storage_phpbridgesessionstorage_ce;

ZEPHIR_INIT_CLASS(Moon_Component_Http_Message_Session_Storage_PhpBridgeSessionStorage);

PHP_METHOD(Moon_Component_Http_Message_Session_Storage_PhpBridgeSessionStorage, __construct);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_PhpBridgeSessionStorage, start);
PHP_METHOD(Moon_Component_Http_Message_Session_Storage_PhpBridgeSessionStorage, clear);

ZEND_BEGIN_ARG_INFO_EX(arginfo_moon_component_http_message_session_storage_phpbridgesessionstorage___construct, 0, 0, 1)
	ZEND_ARG_INFO(0, handler)
	ZEND_ARG_OBJ_INFO(0, metaBag, Moon\\Component\\Http\\Message\\Session\\Storage\\MetadataBag, 0)
ZEND_END_ARG_INFO()

#if PHP_VERSION_ID >= 70200
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_phpbridgesessionstorage_start, 0, 0, _IS_BOOL, 0)
#else
ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_moon_component_http_message_session_storage_phpbridgesessionstorage_start, 0, 0, _IS_BOOL, NULL, 0)
#endif
ZEND_END_ARG_INFO()

ZEPHIR_INIT_FUNCS(moon_component_http_message_session_storage_phpbridgesessionstorage_method_entry) {
	PHP_ME(Moon_Component_Http_Message_Session_Storage_PhpBridgeSessionStorage, __construct, arginfo_moon_component_http_message_session_storage_phpbridgesessionstorage___construct, ZEND_ACC_PUBLIC|ZEND_ACC_CTOR)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_PhpBridgeSessionStorage, start, arginfo_moon_component_http_message_session_storage_phpbridgesessionstorage_start, ZEND_ACC_PUBLIC)
	PHP_ME(Moon_Component_Http_Message_Session_Storage_PhpBridgeSessionStorage, clear, NULL, ZEND_ACC_PUBLIC)
	PHP_FE_END
};
